### ISSUE TITLE
Forceful Tongue - Shouts Overhaul suggestion

### ISSUE THREAD

**Issue by Delta012** [Keizaal/Keizaal#138]
**Mod name**
Forceful Tongue - Shouts Overhaul

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/36276

**Why?**
It is approved by Simon™. Jokes aside, I think the mod gives dignity to the underwhelmed mechanic of shouts. Yes, it's like the innkeeper saying that the wine is good, I know.

**Additional context**
I know that was already suggested before but rejected for balance concerns, and since I'm rebalancing some of the features, eventually I'm open to feedback. Thanks!

**Comment by PierreDespereaux** [comment]
I'll definitely check out what you've done with the mod since I last checked it out!

**Comment by Aosana** [comment]
WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
