### ISSUE TITLE
Less Sarcastic Applause Recommendation

### ISSUE THREAD

**Issue by Aosana** [Keizaal/Keizaal#154]
**Mod name**
Less Sarcastic Applause

**Mod link**
https://www.nexusmods.com/skyrim/mods/66480

**Why?**
This is a tiny animation replacer for clapping that makes it look a tiny bit nicer. It needs to be converted to SSE, of course. (I might port it myself later since it's open permissions.)

**Comment by PierreDespereaux** [comment]
Oh cool, I've meant to try this out a while ago and forgot.

**Comment by Aosana** [comment]
The mod is literally just an .hkx file. I'm not going to bother making a ported page for it. :p
