### ISSUE TITLE
Dropping Venom Sacs into world cause CTD

### ISSUE THREAD

**Issue by WHISKYJVCK** [Keizaal/Keizaal#159]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**
[Save244_CBF97698_0_4A6927446172_Tamriel_002149_20210613142030_24_1.zip](https://github.com/Keizaal/Keizaal/files/6644858/Save244_CBF97698_0_4A6927446172_Tamriel_002149_20210613142030_24_1.zip)
[Crash_2021_6_13_19-29-15.txt](https://github.com/Keizaal/Keizaal/files/6644859/Crash_2021_6_13_19-29-15.txt)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.4.2

**Describe the bug**
Whenever try to drop a venom sac from my inventory (by pressing "r") into the world, as soon as I exit the inventory menu, the game CTDs. So far, this bug has occurred with the Chaurus venom sac and Spider venom sac.

**To reproduce**
1. Open inventory
2. Find a venom sac
3. Press R to drop into the world
4. Exit the inventory screen

**Expected behavior**
After exiting the screen, the venom sacs leave the inventory and live in the world.

**Screenshots**
![Screenshot 2021-06-13 193207](https://user-images.githubusercontent.com/58346522/121825389-17ac9a80-cc80-11eb-926c-810d4b4f3a44.png)

**Additional context**
I couldn't find the object IDs, but I think this is related to "Toxic - A Venom Mod"

**Comment by PierreDespereaux** [comment]
Fixed in Keizaal 4.4.5.
