### ISSUE TITLE
Quest ID MS11 bugged - cannot investigate Hjerim

### ISSUE THREAD

**Issue by WHISKYJVCK** [Keizaal/Keizaal#160]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

[Autosave2_CBF97698_0_4A6927446172_WindhelmHjerim_010030_20210616000728_26_1.zip](https://github.com/Keizaal/Keizaal/files/6659417/Autosave2_CBF97698_0_4A6927446172_WindhelmHjerim_010030_20210616000728_26_1.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.4.3

**Describe the bug**
For quest "Blood on the Ice" (ID MS11) in Windhelm, there are meant to be a list of things to investigate inside Hjerim, but you cannot interact with any items in the house and no prompts for investigations take place. There is also a strange black void in the room to the right when you enter the house (see attached screenshot).

**To reproduce**
1. Enter Hjerim and try to complete the "Look for clues" objective.

**Expected behavior**
You should be able to interact with several clues inside the house. This includes:
1. Investigate Mead: From the dust, these look left over from when the previous occupant moved out.
2. Investigate Chest: From the marks on the floor, it looks like this box was pushed against the wall recently.
3. Investigate Pots and Pans: These haven't been used for ages. Nothing but skeever droppings and cobwebs inside.
4. Investigate Bed and Chairs: The chair is stacked on the bed in an odd fashion.
5. Investigate Wardrobe: This perfectly good wardrobe was left behind for some reason.
6. Investigate Small Shelf: This shelf is filled with more of those "Butcher" fliers from around the city. One pile looks misshapen.
7. Investigate Wardrobe: This wardrobe seems to be nailed to the wall for some reason.
8. Investigate Altar: This altar is built to unknown magic. It looks like someone is using body parts towards some gruesome end.

**Screenshots**
![Screenshot 2021-06-15 201238](https://user-images.githubusercontent.com/58346522/122139478-1497e280-ce17-11eb-9f2b-0332c61c9865.png)

**Additional context**
-

**Comment by PierreDespereaux** [comment]
Fixed in 4.4.4.
