### ISSUE TITLE
Setup Starting problem

### ISSUE THREAD

**Issue by kwaqas131294** [Keizaal/Keizaal#161]
[Wabbajack.current.log](https://github.com/Keizaal/Keizaal/files/6681652/Wabbajack.current.log)
[Wabbajack.current.log](https://github.com/Keizaal/Keizaal/files/6681654/Wabbajack.current.log)
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.4.4

**Describe the bug**
I completely download all the mods but setup fail to install

**To reproduce**
Please fix it

**Expected behavior**
tried every thing even reInstall Skyrim
**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by PierreDespereaux** [comment]
Please do not open a bug report for issues with the Wabbajack client. Bug reports are only for issues you experience while playing the game. If you are having an issue with Wabbajack you should seek help in the Discord server.
