### ISSUE TITLE
Elves Ear Harvestable Model Issues

### ISSUE THREAD

**Issue by Lv1000** [Keizaal/Keizaal#163]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.5.1

**Describe the bug**
Elves Ear harvestables bug out when harvested, making other nearby harvestables change their to their harvested models (they are still harvestable, but display the incorrect model)

**To reproduce**
Scenario: 3 elves ear harvestables are next to each other, you pick one of them, the remaining 2 harvestables now display their harvested models, even tho they haven't been harvested yet, course you can still harvest them. --> come back to those elves ear harvestables later: all 3 harvestables now display their UNHARVESTED models

**Expected behavior**
When an elves ear harvestable is harvested, the models of nearby elves ear harvestables should not change

**Screenshots**
[image 1](https://cdn.discordapp.com/attachments/831186282960912414/860645329145430076/unknown.png)
- This image displays the final part of the scenario in "To Reproduce". an elves ear harvestable (that has been harvested and has not yet respawned) is being targeted by the crosshair. mechanically, the harvestable is harvested, however it displays an unharvested model.

[image 2](https://cdn.discordapp.com/attachments/831186282960912414/860645397838692362/unknown.png)
- This is the same harvestable selected in the console, it is only an example, this happens with all elves ear harvestables regardless of location.

**Additional context**
Unsure if other harvestables have the same issue. Possibly Frost Mirriam

**Comment by PierreDespereaux** [comment]
I can't text anything with just an ESS save. I need the SKSE save too.

**Comment by TateTaylorUSA** [comment]
Fixed in 1.6.0
