### ISSUE TITLE
Proventus will not give bounties

### ISSUE THREAD

**Issue by WulfBearClaw** [Keizaal/Keizaal#164]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
Put the version of the list you are on here.

4.5.1

**Describe the bug**

Talking to Proventus and asking for a bounty has him say that the Jarl has put out a bounty, but you do not get a note, or a quest. Afterwords, he will not have the option to get a bounty again.

**To reproduce**

Simply talk to Proventus and ask for a Bounty. Will be including a save that is at the door of Dragonsreach. Proventus is at the right Dinner Table at the end.

**Expected behavior**

He should give a bounty.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
[Proventus Save.zip](https://github.com/Keizaal/Keizaal/files/6757336/Proventus.Save.zip)

The included save requires The Crossbow Creations, Rare Curios, Vigil Enforcer, Myrwatch, Tundra Homestead, Shadowfoot Sanctum, the Bone wolf and all the patches and addons that go with those

**Comment by PierreDespereaux** [comment]
I can't text anything with just an ESS save. I need the SKSE save too.

**Comment by WulfBearClaw** [comment]
[Proventus Save.zip](https://github.com/Keizaal/Keizaal/files/6758687/Proventus.Save.zip)

Sorry, here's a updated zip with both the ESS and SKSE Save

**Comment by PierreDespereaux** [comment]
There is some script issue between Bounty Preview and Headhunter. I am looking into it.

**Comment by PierreDespereaux** [comment]
Fixed in version 4.5.1.1.
