### ISSUE TITLE
Simple Area Soul Trap

### ISSUE THREAD

**Issue by Lv1000** [Keizaal/Keizaal#166]
**Mod name**
Simple Area Soul Trap

**Mod link**
[Simple Area Soul Trap](https://www.nexusmods.com/skyrimspecialedition/mods/51910)

**Why?**
Adds missing functionality to skyrim, that being AoE soul trap. Since keizaal uses simonrim, the only sources of soul trap are single target, i.e. the spell and firey/regular soul trap enchantments. Mysticism 2 will include a soul cloak type spell but this still leaves a gap for AoE *ranged* soul trap. The mod itself was created to fill this gap and fits seamlessly into mysticism's spell tiers with a patch for leveled lists which is provided.

**Additional context**
N/A

**Comment by PierreDespereaux** [comment]
I'm just not big on it.
