### ISSUE TITLE
Cant Buy houses, Favorite Spells that were hot key'ed just wont work sometimes and some npc's dont do stuff thier meant to  

### ISSUE THREAD

**Issue by Slickydreams** [Keizaal/Keizaal#167]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.4.4

**Describe the bug**
Cant Buy houses ( Dialogue repeats and the house being bought doesn't happen ).
Favorite Spells that were hot keyed just won't work sometimes.
some NPC's don't do stuff their meant to.
Example: the start of the speaking with silence quest for the thieves guild, mercer wouldn't open the door to enter the dungeon
Nightingale hood's Either make the head invincible or work and make the eye part invincible so you still seem headless
Same with Forsworn briar hearts But the chest and leggings are just not there and that happened with every briar heart I found
**To reproduce**
I do not know The spell thing was random
**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
Nightingale hood issue ( https://cdn.discordapp.com/attachments/815251747567304745/860469312955613194/unknown.png )
House not being bought issue (https://cdn.discordapp.com/attachments/678481205930229761/861097446318669913/unknown.png )
**Additional context**
![20210702144617_1](https://user-images.githubusercontent.com/69757887/124387713-3d114f00-dce8-11eb-8d4c-03e6bcfe706e.jpg)
![20210703170911_1](https://user-images.githubusercontent.com/69757887/124387715-3e427c00-dce8-11eb-90d6-aec30e5bc68d.jpg)
![20210704071245_1](https://user-images.githubusercontent.com/69757887/124387717-3e427c00-dce8-11eb-829f-4fbbc088f320.jpg)
![20210702133613_1](https://user-images.githubusercontent.com/69757887/124387718-3edb1280-dce8-11eb-8431-0de446741a30.jpg)
Not really The spell thing randomly happens, the buy house thing started with getting bounties from specific inns where a related issue would happen For the door mercer was meant to open I had to use a console command which fixed the mission after.

**Comment by PierreDespereaux** [comment]
Do you have a savegame you can provide?

**Comment by Slickydreams** [comment]
How do i give that

**Comment by PierreDespereaux** [comment]
Drag and drop your ESS and SKSE saves from Profiles/Keizaal into this comment section.

**Comment by Slickydreams** [comment]
i dont have that folder

**Comment by PierreDespereaux** [comment]
You need to have that folder or Keizaal wouldn't work.

![image](https://user-images.githubusercontent.com/60482452/124388548-6bc00300-dcb1-11eb-8d76-37481a4ca939.png)

This folder.

**Comment by Slickydreams** [comment]
Found it was looking in the install folder

**Comment by Slickydreams** [comment]
It says it doesn't support them do I put them in a zip file and send it here

**Comment by Slickydreams** [comment]
ill just do it

**Comment by Slickydreams** [comment]
[Bug save.zip](https://github.com/Keizaal/Keizaal/files/6760029/Bug.save.zip)

**Comment by PierreDespereaux** [comment]
![image](https://user-images.githubusercontent.com/60482452/124395377-cbc6a180-dcd1-11eb-9139-027f1f3dc707.png)

You have added mods to your Keizaal install. As per Rule 11, in making modifications to your Keizaal install you forfeit all official support you may have received. I suspect most, if not all, of your issues are due to the mods you have added. I would wager the headless Nighingales are almost certainly caused by `Circlets and Masks with all Robes and Hoods.esp`.

I allow discussion of modified Keizaal installs in the #modding channel. I would recommend you head over there and see if anyone there may be able to help.
