### ISSUE TITLE
Dungeons - Revisited

### ISSUE THREAD

**Issue by Zupercharged** [Keizaal/Keizaal#168]
**Mod name**
Dungeons - Revisited

**Mod link**
[Dungeons - Revisited](https://www.nexusmods.com/skyrimspecialedition/mods/51798)

**Why?**
Vanilla+ mod designed to expand vanilla dungeons with alternate routes and dead ends to make them less linear and more interesting to explore.

**Additional context**
Edits 7 dungeons in current version, updates for additional dungeons are to be expected.

**Comment by PierreDespereaux** [comment]
Dungeons - Revisited is already in Keizaal.

**Comment by Zupercharged** [comment]
Apologies, wasnt listed in the modlist when i checked

**Comment by PierreDespereaux** [comment]
Where did you check?

**Comment by Zupercharged** [comment]
https://loadorderlibrary.com/lists/keizaal
Its the list linked on the Wabajack gallery page

http://www.wabbajack.org/#/modlists/search?machineURL=keizaal
This one on the main website is up to date though since it links to the wabajack load order, so ill check that one instead next time.

**Comment by Zupercharged** [comment]
I was searching key words with ctrl+f so i dont think i missed anything

**Comment by PierreDespereaux** [comment]
Ah, yeah that LOL link hasn't been updated since 4.4.0 I'll get that fixed.
