### ISSUE TITLE
Mod-Added Ingredients not standardized w/ Apothecary 

### ISSUE THREAD

**Issue by Lv1000** [Keizaal/Keizaal#169]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.5.2.1

**Describe the bug**
Several mod-added alchemy reagents are not standardized to use Apothecary magnitude/duration values. 

**To reproduce**
Using these ingredients produces irregular potion/poison durations/magnitudes

**Expected behavior**
Potions/Poisons should all be consistent with Apothecary standards when using these ingredients 

**Screenshots**
These are some mod-added ingredients that I found in xEdit. I may have missed some. 
[Image 1](https://cdn.discordapp.com/attachments/831186282960912414/863148038453329950/unknown.png)
[Image 2](https://cdn.discordapp.com/attachments/831186282960912414/863148624162324500/unknown.png)
[Image 3](https://cdn.discordapp.com/attachments/831186282960912414/863149668958732329/unknown.png)
[Image 4](https://cdn.discordapp.com/attachments/831186282960912414/863149859976249354/unknown.png)
[Image 5](https://cdn.discordapp.com/attachments/831186282960912414/863150055649050653/unknown.png)

**Additional context**

**Comment by PierreDespereaux** [comment]
I do not intend of standardizing these ingredients.
