### ISSUE TITLE
Random Naked (non-nude) NPC Found.

### ISSUE THREAD

**Issue by Lv1000** [Keizaal/Keizaal#170]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.5.0 to current (assumed)

**Describe the bug**
Entered a tavern and found this NPC with no clothes on. I'm assuming that this is not intended behavior.

**To reproduce**
Other than trying to spawn this particular NPC, since this was part of a random encounter, I'm not sure how to reproduce. 

**Expected behavior**
NPC should probably be wearing clothes (?)

**Screenshots**
[Image](https://cdn.discordapp.com/attachments/678481205930229761/861072661202993152/unknown.png)

**Additional context**

**Comment by PierreDespereaux** [comment]
I cannot replicate this issue.
