### ISSUE TITLE
Falmer Using Nordic/Skyrim model for Staff instead of Falmer model. 

### ISSUE THREAD

**Issue by Lv1000** [Keizaal/Keizaal#171]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.5.1

**Describe the bug**
Found a staff using the nordic/skyrim staff model on a falmer.

**To reproduce**
Encounter/spawn the falmer shown in the screenshot, otherwise unknown.

**Expected behavior**
Falmer should use Falmer weapons.

**Screenshots**
[Image](https://cdn.discordapp.com/attachments/831186282960912414/862738402099986472/unknown.png)

**Additional context**

**Comment by TateTaylorUSA** [comment]
Let me know if this happens again. I can't seem to find any reason as to why this would be happening.

If it happens again I will reopen this issue and look further.
