### ISSUE TITLE
Cups/Bowls/Jugs/etc sing this design in Bluesky Hall count as stealing 

### ISSUE THREAD

**Issue by Lv1000** [Keizaal/Keizaal#172]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.5.0 to current

**Describe the bug**
Several cups/bowls/jugs/etc in the Bluesky Hall home in Whiterun (expansion mod) count as stealing even tho it is a player owned cell. Screenshots indicate that these items "belong" to the Honningbrew Meadery.

**To reproduce**
Buy the house and look for these items (with the same art style shown in the screenshot.

**Expected behavior**
They shouldn't be tagged as stealing.

**Screenshots**
This is just *one* example, there are quite a few more.
[Image](https://cdn.discordapp.com/attachments/678481205930229761/861825936353918986/unknown.png)

**Additional context**

**Comment by PierreDespereaux** [comment]
Fixed in 4.5.2.2
