### ISSUE TITLE
Frozen Electrocuted Combustion

### ISSUE THREAD

**Issue by Kosoumi** [Keizaal/Keizaal#174]
**Mod name**
Frozen Electrocuted Combustion

**Mod link**
[https://www.nexusmods.com/skyrimspecialedition/mods/3532](https://www.nexusmods.com/skyrimspecialedition/mods/3532)

**Why?**
Really helps add immersion to the magic system by seeing the visceral damage magic does. Doesn't change magic whatsoever, only adds visual effects to fallen enemies.

**Additional context**
N/A

**Comment by PierreDespereaux** [comment]
I just find it a little cartoony and unnecessary.
