### ISSUE TITLE
Lux looks sick

### ISSUE THREAD

**Issue by Bananaaaaaaaaaaa** [Keizaal/Keizaal#175]
**Mod name**
Lux

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/43158

**Why?**
Seen someone test this and it looks brilliant. 

**Additional context**
The person testing the mod was quite experienced in modding skyrim and according to them, this is the best of its kind.

**Comment by PierreDespereaux** [comment]
Lux is very pretty but too dark for my taste, plus it took a while to get to a lighting setup that I was happy with. My current suite is fine.
