### ISSUE TITLE
Better Stealing makes so much sense

### ISSUE THREAD

**Issue by Bananaaaaaaaaaaa** [Keizaal/Keizaal#176]
**Mod name**
Better Stealing

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/32295

**Why?**
This makes sense since people can't track items unless they are one of a kind. 

**Additional context**
There is a value limit that adds the stolen tag to Unique or expensive items.

**Comment by PierreDespereaux** [comment]
I am worried this will make finding fences less important.
