### ISSUE TITLE
All versions of the Miraak Mask horribly clip with long hair and beards

### ISSUE THREAD

**Issue by WulfBearClaw** [Keizaal/Keizaal#177]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
4.5.2.2

**Describe the bug**
A versions of Miraaks mask horribly clip with long hair and beard styles.

**To reproduce**
Have a long hair style and beard and wear the miraak mask. Here's an ID you can use to add one of the 6 different mask: 04039D2F

**Expected behavior**
Hair and beards should not clip through the mask

**Screenshots**
![489830_20210712130418_1](https://user-images.githubusercontent.com/35999389/125335074-c096f580-e311-11eb-8f2a-30eb0f42074f.png)

![489830_20210712130421_1](https://user-images.githubusercontent.com/35999389/125335110-cab8f400-e311-11eb-8b00-665e7ed05e63.png)

**Additional context**
Here's a save with a character with long hair, a long beard and all the Miraak Mask: 
[Miraak Mask Save.zip](https://github.com/Keizaal/Keizaal/files/6803483/Miraak.Mask.Save.zip)

**Comment by PierreDespereaux** [comment]
It's either this or no Improved Closed-face Helmet meshes.
