### ISSUE TITLE
Royal Armory

### ISSUE THREAD

**Issue by Bananaaaaaaaaaaa** [Keizaal/Keizaal#178]
**Mod name**
Royal Armory

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/6994

**Why?**
It makes sense for the important NPCs to have unique looking weapons and these look amazing.

**Additional context**
N/A

**Comment by PierreDespereaux** [comment]
I really *want* to like this mod. As it stands, I would need to make some personal edits to be happy with it in Keizaal.
