### ISSUE TITLE
Dragon Carved Armor

### ISSUE THREAD

**Issue by Iccotak** [Keizaal/Keizaal#179]
**Mod name**
Dragon Carved Armor

**Mod link**
Special Edition Link: https://www.nexusmods.com/skyrimspecialedition/mods/4253
Original Mod: https://www.nexusmods.com/skyrim/mods/66130/?

**Why?**
I think it fits thematically well with Skyrim and with the aims of Keizaal, also it is a well designed armor. Very Cool and Very Vanilla Friendly

**Additional context**
Sample Images of the Mod
![66130-39-1432224065](https://user-images.githubusercontent.com/87349569/125381960-4e3e0980-e341-11eb-99bf-9092fff9eabb.jpg)
![66130-0-1435173172](https://user-images.githubusercontent.com/87349569/125381970-5138fa00-e341-11eb-91d9-3b442b4508ab.jpg)
![66130-25-1432224068](https://user-images.githubusercontent.com/87349569/125382018-63b33380-e341-11eb-9831-60c5093b2a1a.jpg)

**Comment by PierreDespereaux** [comment]
I don't think it looks different enough for vanilla Nordic Armor for its inclusion to be worth it.
