### ISSUE TITLE
Worthy of a prince

### ISSUE THREAD

**Issue by Bananaaaaaaaaaaa** [Keizaal/Keizaal#180]
**Mod name**
Umbral Embrace

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/51715

**Why?**
Vanilla Nocturnal looks human. Disgusting. Now she looks more daedric and ominous.
**Additional context**
[
![image](https://user-images.githubusercontent.com/87282867/125450904-9514fcf1-e09e-4bc2-a30c-a8634ce94dd3.png)
](url)

**Comment by PierreDespereaux** [comment]
I am personally a fan of Vanilla Nocturnal.
