### ISSUE TITLE
Menacing Alduin

### ISSUE THREAD

**Issue by Iccotak** [Keizaal/Keizaal#181]
**Mod name**
Menacing Alduin

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/50732

**Why?**
A more lore accurate depiction of Alduin that sticks more closely to the source Art Material than the current Alduin mod in the list. This overall makes Alduin look like an intimidating existential threat to Nirn - rather than a generic Dragon

**Additional context**
![50732-1622644242-435536774](https://user-images.githubusercontent.com/87349569/125450981-047e5e67-d755-442d-a4be-b29b18593bb7.png)

**Comment by PierreDespereaux** [comment]
I went through several Alduin retextures a few updates back and I am *very* happy with Rustic Dragons + Ald Son of Ald + Alduin Particle Light Eyes.
