### ISSUE TITLE
Seagulls of Skyrim

### ISSUE THREAD

**Issue by WulfBearClaw** [Keizaal/Keizaal#182]
**Mod name**
Seagulls of Skyrim

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/52153

**Why?**
Adds a bit more immersion to the game by adding seagulls near populated ports. Replaces the weird hawks in places like Solitude. Doesn't make any sense that there would be like 20 hawks in one place, their a predatory bird that tends to be territorial.

**Comment by PierreDespereaux** [comment]
I *really* wanted to like this mod, but the sound effects began to annoy me after only five minutes of testing the mod.
