### ISSUE TITLE
First Person Camera Doesn't Match Player Character Height

### ISSUE THREAD

**Issue by xii7** [Keizaal/Keizaal#183]
**Keizaal version**
4.5.1

**Describe the bug**
 Male Nord player character height is reduced in first-person

**To reproduce**
Steps to reproduce the behaviour: 

The bug just simply happens with time.
* Load Save 12. which loads with the correct player height. 
* Line up with Faendal.
* Go into third-person view.
* Go back into first-person view.
* The player height will shrink within a minute.

**Expected behaviour**
Player character to always remain at the same height in first-person

**Screenshots**
![ScreenShot27](https://user-images.githubusercontent.com/49735943/126026636-c2a4befa-9bd9-4d91-a8c2-3c001949d7e0.png)
![ScreenShot28](https://user-images.githubusercontent.com/49735943/126026756-ead26705-77e0-4d8f-a2d5-ed90893c685a.png)

**Additional context**
This has happened on numerous Keizaal versions and multiple new games. 

I had previously reported that this bug seems to occur after leaving Bleak Falls Barrow, but after going back to my last save within the dungeon I found that the bug does still happen before leaving. I can't be certain when it starts.

[saves.zip](https://github.com/Keizaal/Keizaal/files/6834209/saves.zip)

**Comment by PierreDespereaux** [comment]
Fixed in 4.5.4.
