### ISSUE TITLE
Wearable Lanterns

### ISSUE THREAD

**Issue by spooknik** [Keizaal/Keizaal#184]
**Mod name**
Wearable Lanterns 

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/7560
https://www.nexusmods.com/skyrimspecialedition/mods/25372

**Why?**
Gives a purpose to the lanterns you find in Skyrim. I feel the system blends well into vanilla Skyrim. When a player sees a lantern they know what it's for but the vanilla game marks it as junk. Unlike torches the lanterns allow you to use two handed weapons. 

**Additional context**
I witnessed someone new to the game find a lantern but couldn't find a use for it.

**Comment by TateTaylorUSA** [comment]
I have never really liked this mod.
