### ISSUE TITLE
Skyrim.scc not downloading

### ISSUE THREAD

**Issue by y0gib3ar** [Keizaal/Keizaal#185]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Keizaal version**
Keizaal 4.5.4

**Describe the bug**
Skyrim.ccc  download is broken, so installing won't start

**To reproduce**
Trying to download the complete archive with Wabbajack but Skyrim.ccc fails, hashed download is incorrect.
Also trying to find a solution fails

**Expected behavior**
Well, at least the downloads should complete correctly which it does not.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
Retrying download giving the following output (current log).

18437,31 - Starting to install Keizaal
18437,32 - Starting Installer Task
18437,32 - Installation has Started
18437,32 - File hash check (-42) a56ffc3e0acbdc83763d2ba2c6f9887855e27d4063f0c1f4a33eb69711610c00
18437,52 - Configuring Processor
18437,52 - Install Folder: D:\Games\02-GameTools\MO2\ABD_GameProfiles\Skyrim SE\Keizaal
18437,52 - Downloads Folder: E:\03-GameActiveStuff\SkyrimSE\ModOrganizer\Keizaal\downloads
18437,52 - Game Folder: D:\Games\SteamLibrary\steamapps\common\Skyrim SE
18437,53 - Wabbajack Folder: D:\Wabajack\2.5.1.2
18437,53 - Drive watcher is starting. Will warn at 8GB and error at 4GB
18437,53 - Starting Drive watcher on D:\ currently 293,4GB free out of 368,1GB
18437,53 - Starting Drive watcher on E:\ currently 148,5GB free out of 931,5GB
18437,53 - Validating Game ESMs
18437,53 - Creating Output Folders
18437,61 - Optimizing ModList
18437,61 - Optimizing ModList directives
18438,76 - Looking for files to delete
18438,76 - Cleaning empty folders
18440,05 - Looking for unmodified files
18440,74 - Updating ModList
18440,74 - Optimized 72975 directives to 72975 required
18440,77 - Hashing Archives
18440,77 - Looking for files to hash
18441,84 - Found 1032 total files, 849 matching filesize
18443,39 - Downloading Missing Archives
18443,4 - Missing 1 archives
18443,4 - Getting Nexus API Key, if a browser appears, please accept
18443,4 - Loading server whitelist
18443,61 - Loaded permissions for 469 servers and 233 Google Drive files
18443,61 - File hash check (-42) a56ffc3e0acbdc83763d2ba2c6f9887855e27d4063f0c1f4a33eb69711610c00
18443,64 - Downloading Skyrim.ccc
18443,66 - Hashed download is incorrect
18444,25 - Trying to find solution to broken download for Skyrim.ccc
18444,25 - Looking for generic upgrade for yLhCbCSfkuE= (-2192515089792059192)
18444,87 - Looking for generic upgrade for yLhCbCSfkuE= (-2192515089792059192)
18445,05 - No solution for broken download Skyrim.ccc GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim.ccc could be found
18445,09 - Hashing Remaining Archives
18445,09 - Looking for files to hash
18446,15 - Found 1032 total files, 849 matching filesize
18447,71 - Unable to download Skyrim.ccc (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim.ccc)
18447,71 - Cannot continue, was unable to download one or more archives
18447,71 - File hash check (-42) a56ffc3e0acbdc83763d2ba2c6f9887855e27d4063f0c1f4a33eb69711610c00
18447,72 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 211
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
18447,89 - File hash check (-42) a56ffc3e0acbdc83763d2ba2c6f9887855e27d4063f0c1f4a33eb69711610c00

**Comment by TateTaylorUSA** [comment]
Please do not open a bug report for issues with the Wabbajack client. Bug reports are only for issues you experience while playing the game. If you are having an issue with Wabbajack you should seek help in the Discord server.
