### ISSUE TITLE
These weapons look slick yo

### ISSUE THREAD

**Issue by Bananaaaaaaaaaaa** [Keizaal/Keizaal#186]
**Mod name**
Believable weapons

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/37737

**Why?**
These weapons look much more realistic and slick. They are high quality and the swords come with sheathes.

**Comment by TateTaylorUSA** [comment]
Believable Weapons takes the vanilla aesthetic and throws it away for "realism". These weapons are more "believable", yes, but at the cost of the unique design of each weapon tier.

Keizaal has Better Shaped Weapons which thins out the paddle-blade swords nicely while retaining the vanilla design.

**Comment by Bananaaaaaaaaaaa** [comment]
You are right. This was an impulsive suggestion.
