### ISSUE TITLE
Closed Cities Skyrim

### ISSUE THREAD

**Issue by KaptainCnuckz** [Keizaal/Keizaal#187]
**Mod name**
Closed Cities Skyrim

**Mod link**
https://www.nexusmods.com/skyrim/mods/102051

**Why?**
Boosts the immersion levels immersively in an immersive manner. Now the city truly is closed, due to the dragon attack.

**Additional context**
![image](https://user-images.githubusercontent.com/76413382/126396981-77063175-355f-4532-b455-fe6c8dbc150c.png)

**Comment by TateTaylorUSA** [comment]
what the fuck Kap?
