### ISSUE TITLE
Unable to download xLODGen.82.7z

### ISSUE THREAD

**Issue by mrcofffeee** [Keizaal/Keizaal#189]
Hi there,

I'm receiving this error when trying to automatically install Keizaal: Unable to download xLODGen.82.7z, it seems the mega link is broken. 

log says:

269.34 - Unable to download xLODGen.82.7z (MegaDownloader+State|https://mega.nz/#!xdwmmKgA!I_KNynb4Fz0mrQV8bxBNlgw42KUykkk2VhM1RRkn5ts)
269.34 - Cannot continue, was unable to download one or more archives

Any way to update this? I can't seem to finalize the installation without it. 

Thanks,
Cofffeee

edit: typo

**Comment by TateTaylorUSA** [comment]
Fixed in 1.6.0.1.
