### ISSUE TITLE
Mod Suggestion - Gemstones Replacers HD SE

### ISSUE THREAD

**Issue by Lv1000** [Keizaal/Keizaal#191]
**Discord Username**
Aerin#8230

**Mod name**
Gemstones Replacers HD SE

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/46531

**Why?**
Why do you think this mod should be included in Keizaal?
While this is, at it's core, a retexture/replacer mod (and a good one at that), I really like that it visually distinguishes regular and flawless gems by adding cracks, haziness, and/or other blemishes to regular gems. This is the first mod I've found that does this in an effective, yet subtle way. 

**Additional context**
N/A

**Comment by TateTaylorUSA** [comment]
Added in Keizaal 4.6.2.
