### ISSUE TITLE
Mammoth bones look like plastic... (Higher quality mammoth bone retexture recommendation.)

### ISSUE THREAD

**Issue by wolfgarr15** [Keizaal/Keizaal#192]
**Discord Username**
TwoArmedMan15

**Mod name**
Unreal 4K-8K Mammoth Skeleton Retexture

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/39356?tab=files

**Why?**
The vanilla mammoth bones looks like plastic. No amount of upscaling/sharpening can fix that, so Project Clarity/Base Coat don't look better. The recommended mod is higher quality and still fits the vanilla theme. (Bleached bone, not yellowed like other retextures.) 

**Additional context**
Despite the recommended mod's name, there is a 2K option in the file downloads and it still looks excellent.

**Comment by TateTaylorUSA** [comment]
I will look for a Mammoth Bone re-texture, but this isn't it. It looks off to me.
