### ISSUE TITLE
The Ultimate Dodge Mod

### ISSUE THREAD

**Issue by SimoneBorrelli** [Keizaal/Keizaal#193]
**Discord Username**
raziel2734

**Mod name**
TUDM - The Ultimate Dodge Mod

**Mod link**
https://drive.google.com/file/d/0B2VgBVA9jE6RTjJiYnRTTE9qRUE/view?resourcekey=0-atMbrLF_HPd3ogbiZaBiXw

**Why?**
Great for the immersion, Great for the Gameplay :)

**Comment by TateTaylorUSA** [comment]
Dodge mods don't fit in Keizaal.
