### ISSUE TITLE
Animated Clutter SSE - Strongbox Option ONLY

### ISSUE THREAD

**Issue by Lv1000** [Keizaal/Keizaal#194]
**Discord Username**
Aerin#8230

**Mod name**
Animated Clutter SSE

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/14398

**Why?**
Why do you think this mod should be included in Keizaal?
Note: This is only for the strongbox option in the fomod. 
In vanilla Skyrim (and Keizaal) strongboxes don't have opening/closing sounds (completely silent) and it's a bit funky once you notice it. The strongbox option from this mod adds these missing opening/closing sounds, simple as that!

**Additional context**
N/A

**Comment by TateTaylorUSA** [comment]
I'll have to think about it 64MB isn't big, but it is pretty big for just being a single sound.

**Comment by TateTaylorUSA** [comment]
Will be included in Keizaal 5.1.0.
