### ISSUE TITLE
Footprints - mod recommendation

### ISSUE THREAD

**Issue by eraser2011** [Keizaal/Keizaal#195]
**Mod name**
Footprints

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/3808?tab=description

**Why?**
Keizaal achieves a wonderful and stunning look, especially the snowy scenery is looking great. But there is something missing. The recommended mod would bring footprints into the game and add to the visuals and realism.

**Comment by TateTaylorUSA** [comment]
Footprints is an infamously poorly made mod that is responsible for destroying many a savegame.
