### ISSUE TITLE
Missing Text in UI

### ISSUE THREAD

**Issue by eraser2011** [Keizaal/Keizaal#196]
**Keizaal version**
5.0.0

**Describe the bug**
After the newest 5.0.0 update (thanks btw :), I have a few UI bugs. ~~In the quick loot menu there is missing text for weight and stats and~~ The notification for sneak attacks/critical hits is missing

**To reproduce**
Happens every time. Even on a completely fresh save, no modifications whatsoever.
![Bug](https://user-images.githubusercontent.com/5322911/129397623-6ffd1a85-8ab2-44ca-8036-78c0e8930dec.jpg)

**Comment by eraser2011** [comment]
Disabling "powerofthree's Tweaks" gets rid of the missing sneak/critical hit notification bug

**Comment by eraser2011** [comment]
ok, no bug here. It's just a setting turned on in the po3_Tweaks.ini.
I still would like to see this message on by default.

**Comment by TateTaylorUSA** [comment]
Hey, actually I didn't want that tweak enabled. So I'll be sure to have that turned off in the future.

**Comment by eraser2011** [comment]
I don't know why it's even turned on by default. It's in the tweaks category which should be disabled by default.
