### ISSUE TITLE
Random CTD when exiting Dragonsreach

### ISSUE THREAD

**Issue by Jarendron** [Keizaal/Keizaal#197]
[Crash_2021_8_21_8-32-34.txt](https://github.com/Keizaal/Keizaal/files/7025939/Crash_2021_8_21_8-32-34.txt)
[Crash_2021_8_21_11-30-57.txt](https://github.com/Keizaal/Keizaal/files/7025940/Crash_2021_8_21_11-30-57.txt)

**Discord Username**
Jardenon

**Keizaal version**
5.0.1

**Describe the bug**
CTD after exiting dragonsreach

**To reproduce**
it happens randomly when exiting dragonsreach

**Expected behavior**
No CTD

**Comment by TateTaylorUSA** [comment]
Please try disabling EVG Animation Variance and see if your crashing continues.
