### ISSUE TITLE
Carriage and Ferry Overhaul

### ISSUE THREAD

**Issue by ToastySpaghet36** [Keizaal/Keizaal#198]
**Discord Username**
- ToastySpaghet36#9362

**Mod name**
Carriage and Ferry Travel Overhaul

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/8379

**Why?**
This is a great mod and it is the overhaul that vanilla needs without being too out there. 

**Additional context**
It allows for travel to villages and homesteads from the major city stables. Journey prices now depend on the distance travelled. It also adds carriages to cities that before didnt have any (Falkreath, Morthal and Dawnstar). It also allows for ferry travel along the coast, solstheim and certain lakes.

**Comment by TateTaylorUSA** [comment]
I've tried it before and I do not like it.

**Comment by ToastySpaghet36** [comment]
aight no worries
