### ISSUE TITLE
Meeko mod recommendation

### ISSUE THREAD

**Issue by ChaoHellsing** [Keizaal/Keizaal#199]
ChaoHellsing

Improved Meeko SE

https://www.nexusmods.com/skyrimspecialedition/mods/8165

Because Meeko looks really nice in Keizaal, and the pupper needs more love.

The mod author also has listed anyone can use change and redistriute without asking any permissions.

**Comment by TateTaylorUSA** [comment]
This is in compatible with my current Meeko mod, but I will look into making similar tweaks myself.

**Comment by ChaoHellsing** [comment]
That works for me. That still means Meeko gets some love.
