### ISSUE TITLE
Fixes for the butterflies

### ISSUE THREAD

**Issue by Jarendron** [Keizaal/Keizaal#200]
**Discord Username**
Jardenon

**Mod name**
Butterfly Improved by zzjay - SE

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/37302

**Why?**
This is a simple aesthetic fix to butterflies in Skyrim SE. the monarch butterflies in vanilla Skyrim have always notoriously had an error where the wings are upside down. This mod not only fixes that issue, but also improves the overall appearance of the butterflies in a lore-friendly manner.

**Additional context**
A followup mod would also go well with this mod. I will be suggesting that one as well.

**Comment by TateTaylorUSA** [comment]
Will be included in Keizaal 5.1.0.
