### ISSUE TITLE
Futher Butterfly fixes

### ISSUE THREAD

**Issue by Jarendron** [Keizaal/Keizaal#201]
**Discord Username**
Jardenon

**Mod name**
Butterflies Land True

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/29434?tab=description

**Why?**
This is a followup to my previous suggestion (#200) This mod further fixes the butterflies to where they land properly and works well in tandem with my previous butterfly fix suggestion. This suggestion is for further improving the immersion of the game by fixing where the butterflies land.

**Additional Context**

**Comment by TateTaylorUSA** [comment]
Already included in Keizaal.
