### ISSUE TITLE
G.R.I.M Dawngaurd Overhaul suggestion.

### ISSUE THREAD

**Issue by BlazeWarfaree** [Keizaal/Keizaal#202]
**Discord Username**
Blaze#3795

**Mod name**
G.R.I.M

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/41816

**Why?**
Why do you think this mod should be included in Keizaal?
The vanilla dawngaurd reaper boss fight has much to be desired. He looks like utter garbage and is a horribly unfun boss fight. The vanilla Reaper’s AI is so screwed up that he never even attacks you, just stands at range and spits afflicted poison. All that work collecting the gems, all that anticipation and awe from the narration of the souls, and for what? i feel this while a small issue in my opinion should be changed to make for a more interesting experiance whilst exploring the cairn during the dawngaurd dlc.
the mod provides replayablity and makes the boss fight scale with the player along with getting harder and harder every time you do it providing some more near end game things to do in a deeply invested save. 

**Additional context**
going to attach a before and after of visual overhauls made to the boss as well
https://i.imgur.com/fqTVsjy.png
https://staticdelivery.nexusmods.com/mods/110/images/105274/105274-1603922831-1372987046.png

**Comment by TateTaylorUSA** [comment]
This mod is a little too much for my taste.
