### ISSUE TITLE
Making Konahrik Worth Getting/General Dragon Priest Gear Improvements

### ISSUE THREAD

**Issue by RenaGANG** [Keizaal/Keizaal#203]
**Discord Username**
RenaGANG

**Mod name**
Konahrik's Accountrements

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/22206#:~:text=About%20this%20mod%20%20%20%20Mod%20name,%20%20Imagine.%20%2012%20more%20rows%20

**Why?**
The named/masked Dragon Priests were supposed to be the absolute top of food chain in their society. The most powerful mages mankind had at the time. Their masks were created as the ultimate reward for their fealty and dedication to their dragon masters, as well as for their absolute control over the populace. And they're not. They suck. Almost all of them. The Konahrik mask itself, the final reward for collecting all eight high priest masks and the mask of like THE TOP PRIEST, is one of the most useless and is a massive disappointment after putting in all the work to get it. This mod fixes that perfectly in my opinion. In addition, it also adds a cool new quest and dungeon, wearable Dragon Priest armor, and some other rad things.

**Additional context**

**Comment by TateTaylorUSA** [comment]
I am currently looking forward to an unnamed indev Dragon Priest armor mod. That mod will supersede Accountrements.
