### ISSUE TITLE
Lucien Werewolf bug

### ISSUE THREAD

**Issue by Jarendron** [Keizaal/Keizaal#205]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

**Discord Username**
Jardenon

**Keizaal version**
5.1.0

**Describe the bug**
My character is a werewolf. Made so during the companions quest line. while bringing Esburn back to Riverwood, my character turned into a werewolf spontaneously. Riverwood's guards became hostile, so I ran from town. Lucien Flavious was in my party when I ran. I used the revert form power, and then Lucien started to attack me. 

**To reproduce**
Unknown

**Expected behavior**
Lucien Shouldn't be attacking me.

**Screenshots**
None

**Additional context**
None

**Comment by TateTaylorUSA** [comment]
I cannot reproduce this. If you have a savegame from around when you experienced the bug please provide it to me (along with the SKSE co-save).

If you do not, just let me know if you experience this bug again.

**Comment by Jarendron** [comment]
I cannot reproduce this bug either. and I tried 4 times now.
