### ISSUE TITLE
Immersive Khajiit Caravan Mules

### ISSUE THREAD

**Issue by Kosoumi** [Keizaal/Keizaal#206]
**Discord Username**
Kosoumi#2049

**Mod name**
Immersive Khajiit Caravan Mules

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/49058

**Why?**
I've always found it a little odd that the Khajiit caravan wanders all across Skyrim without a means to carry all their tents and goodies. This mod aims to fix that by providing the caravan with it's own mules that visually carry crates and tents.

**Additional context**
From the modpage: "It seems that Bethesda originally envisioned for the Khajiit Caravans to have horse accompanying the caravan; there is an unused template for CaravanHorses in the game files (if you check in xEdit you can see I actually referred to this template :). I guess this mod kind of delivers what was already envisioned by Bethesda!"

**Comment by TateTaylorUSA** [comment]
Will be added to Keizaal 5.1.2.
