### ISSUE TITLE
High Hrothgar Fixed

### ISSUE THREAD

**Issue by KaptainCnuckz** [Keizaal/Keizaal#207]
**Discord Username**
KaptainCnucklz#4994

**Mod name**
High Hrothgar Fixed

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/55254

**Why?**
Fixes minor bugs in the meshes of High Hrothgar. It also adds window panes to the exterior walls like the interior walls had (which have a nice subtle glow). As a bonus smooths the fairly low poly fire bowls that they use for lights.

**Additional context**
Example of the missing exterior windows:
![55254-1631223163-796988856](https://user-images.githubusercontent.com/76413382/132821730-e8914fd3-2707-4662-ab8f-500083cf3e08.jpeg)
Weird missing bit in the ceiling, that creates a weird tunnel in the roof:
![55254-1631223995-1296301763](https://user-images.githubusercontent.com/76413382/132821777-b4346480-09de-4398-b40f-cfb868040e98.jpeg)
The neat glowing window effect I mentioned:
![55254-1631042573-943459079](https://user-images.githubusercontent.com/76413382/132821928-fcbc1064-7d2a-4ebb-8b9c-4ddcb46834b4.jpeg)

These screenshots were from the main page. The mod has no plugin and is only replacer meshes, so it's hopefully a bonus as far as compatibility goes.

**Comment by TateTaylorUSA** [comment]
Added in the Obsidian Update.
