### ISSUE TITLE
Whiterun horse floating player bug

### ISSUE THREAD

**Issue by Jarendron** [Keizaal/Keizaal#208]
**Discord Username**
Jardenon

**Keizaal version**
5.1.1

**Describe the bug**
I try to buy the horse outside of Whiterun. Then I mount up on the horse. I fall through the horse and the player floats around while also controlling the horse. The horse and the player move in different directions. It is impossible to "dismount" once this bug has occurred.

**To reproduce**
Purchase the horse in Whiterun. Mount the horse while it is standing inside the stable. Your character will fall thorough the horse, and you will then be able to control the player. The player will float around, and the horse will move away from the player in a different direction form the player.

**Expected behavior**
It is very clear that the game shouldn't be doing this when you mount a horse.

**Screenshots**
![ScreenShot5](https://user-images.githubusercontent.com/83714085/133913345-4ef82e09-b75c-412a-9ccd-caa5f3a5cd9d.png)

**Comment by TateTaylorUSA** [comment]
I cannot reproduce this. If you have a savegame from around when you experienced the bug please provide it to me (along with the SKSE co-save).

If you do not, just let me know if you experience this bug again.
