### ISSUE TITLE
Convenient Horses

### ISSUE THREAD

**Issue by Jarendron** [Keizaal/Keizaal#211]
**Discord Username**
Jardenon

**Mod name**
Convenient horses

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/9519

**Why?**
After using a horse for a while, I kinda miss being able to find my horse easily after getting in a fight. I will be out in the prairie, and my horse will run off whenever wolves, bandits or a sabercat chase after me, and because I can't always see where my horse ran, I sometimes lose the horse for a while. So I figured since this isn't any bigger game change than some of the other mods used in Keizaal, I figured this one would be really good to add. it makes using horses a lot more enjoyable. It's a very straightforward mod.

**Comment by TateTaylorUSA** [comment]
This feature is already present in Keizaal.
https://keizaal.github.io/Keizaal/INSTALLATIONGUIDE.html#hotkeys
