### ISSUE TITLE
Nordic UI

### ISSUE THREAD

**Issue by Faolan2021** [Keizaal/Keizaal#213]
**Discord Username**
faolan

**Mod name**
Nordic UI

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/49881

**Why?**
It's an interesting alternative to other UI's, vanilla or otherwise.

**Additional context**

![image](https://user-images.githubusercontent.com/92000360/136123078-17d4e417-5393-40d7-9e65-268afcf24fc9.png)

**Comment by TateTaylorUSA** [comment]
Incompatible with several essential mods, namely [CoMAP](https://www.nexusmods.com/skyrimspecialedition/mods/56123).
