### ISSUE TITLE
DLC integration

### ISSUE THREAD

**Issue by Faolan2021** [Keizaal/Keizaal#214]
**Discord Username**
faolan
**Mod name**
DLC Integration SE

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/8032

**Why?**
I like to think it helps bind the game's disparate content together.

**Additional context**
![image](https://user-images.githubusercontent.com/92000360/136629135-b63d0c97-77d7-43a3-9b35-92349d43b833.png)

**Comment by TateTaylorUSA** [comment]
I have mods that already cover the majority of the DLC integration features I like. The rest I am not into.
