### ISSUE TITLE
Skyland AIO Update

### ISSUE THREAD

**Issue by Dwailing** [Keizaal/Keizaal#217]
**Discord Username**
Dwailing#5896

**Mod name**
Skyland AIO v2.0.1

**Mod link**
https://www.nexusmods.com/skyrimspecialedition/mods/34179

**Why?**
Skyland has always been an impressive texture set, but the new update to it really looks like it's really getting pushed to the next level. While it does deviate slightly from the vanilla style in a few places, I think it's hard to argue that it isn't one of the most impressive sets currently available, and the latest update seems to actually bring it closer to the vanilla aesthetic. I think it would make a great addition to Keizaal that would fit very nicely with its core philosophy while bringing Skyrim more in line with the visual quality expected from a AAA game in 2021.

**Comment by TateTaylorUSA** [comment]
It is an impressive feat but I've always found Skyland to be a little off. I've tried several of their retextures before.
