### ISSUE TITLE
Missing Dragonsreach Assets and Purple Main Door Textures. 

### ISSUE THREAD

**Issue by StarfleetCommand** [Keizaal/Keizaal#226]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

**Discord Username**
Amphithoe#4430

**Keizaal version**
6.0.0.2

**Describe the bug**
A piece of the exterior of Dragonsreach main hall is missing, leaving the top floating in mid-air.  Additionally the textures on the main hall door is missing. 

**To reproduce**
Install the mod list as per normal.

**Expected behavior**
Dragonsreach building should display as normal and doors should have textures assigned. 

**Screenshots**
![ScreenShot19](https://user-images.githubusercontent.com/17068023/141615039-0c05d444-66fb-4e20-bf34-f44c0811e7c7.png)

**Additional context**

**Comment by TateTaylorUSA** [comment]
Fixed in 6.0.0.3
