### ISSUE TITLE
Open_Cities_Skyrim.7z hash failed

### ISSUE THREAD

**Issue by alic3woodstock** [Keizaal/Keizaal#228]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

**Discord Username**
Alice Woodstock#5856

**Keizaal version**
6.0.1.2

**Describe the bug**
Wabbajack is unable to download Open_Cities_Skyrim.7z due to incorrect hash

**To reproduce**
Just try to intall the mod for the first time

**Expected behavior**
Download all archives and start intall
[Wabbajack 2021-12-07 14_57_55.log](https://github.com/Keizaal/Keizaal/files/7670741/Wabbajack.2021-12-07.14_57_55.log)

**Comment by TateTaylorUSA** [comment]
Please do not open a bug report for issues with the Wabbajack client. Bug reports are only for issues you experience while playing the game.

Keizaal is currently down, I will need to manually recompile it before people are able to download it again.
