### ISSUE TITLE
Open Cities mod needs to be updated

### ISSUE THREAD

**Issue by DeividDAVE** [Keizaal/Keizaal#229]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

**Discord Username**
DavidDAVE#7681

**Keizaal version**
Put the version of the list you are on here.

**Describe the bug**
Wabbajack fails during installation because is unable to download Open_Cities_Skyrim.7z mod. It has been updated on moddb and it doesnt find the file anymore.

**To reproduce**
Launching installation on Wabbajack

**Expected behavior**
Mod not on the list, or updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/67625148/145367234-aa8b2384-b6f3-4ce3-b757-27e9864d513a.png)

Thanks a lot in advance!!

**Comment by TateTaylorUSA** [comment]
Please do not open a bug report for issues with the Wabbajack client. Bug reports are only for issues you experience while playing the game.

Keizaal is currently down, I will need to manually recompile it before people are able to download it again.
