### ISSUE TITLE
CTD in House of Horrors

### ISSUE THREAD

**Issue by oswaltdw** [Keizaal/Keizaal#230]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**
[Crash_2022_1_3_22-17-30.txt](https://github.com/Keizaal/Keizaal/files/7808857/Crash_2022_1_3_22-17-30.txt)

**Discord Username**
Blessed_by_Arkay#1248

**Keizaal version**
6.1.0.1

**Describe the bug**
The second door inside the abandoned house would not open and there was no key. Grabbed everything in the house looking for a key or something and got a ctd

**To reproduce**
Might have entered the house at too low a level...idk

**Expected behavior**
The second door is supposed to open somehow. Idk why it had a crash.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TateTaylorUSA** [comment]
I was unable to replicate this. If you experince this again let me know and I will reopne this issue.

Sorry for taking so long to reply.
