### ISSUE TITLE
BTPS showing Trap Linkers

### ISSUE THREAD

**Issue by YamiOfTenshi** [Keizaal/Keizaal#231]
Yami no Tenshi

6.3.1

BTPS appears to pick up on CK things like Trap Linkers.

Walk to a Trap Linker

Trap Linker will appear

![image](https://user-images.githubusercontent.com/60445070/156945406-88eac071-992a-48f2-9302-540025115a3a.png)

Noticed near the campsite with the dead NPCs just a bit north of Old Hroldan.

**Comment by TateTaylorUSA** [comment]
Should be resolved in 6.3.1.1.
