### ISSUE TITLE
Crash on revert from Vampire Lord form

### ISSUE THREAD

**Issue by Arioh002** [Keizaal/Keizaal#232]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**
No logs available

**Discord Username**
Arioh002

**Keizaal version**
6.4.0.1

**Describe the bug**
Crash to desktop on attempt to revert from Vampire Lord form.

**To reproduce**
1. Get Vampire Lord form
2. Complete lessons with Harkon
3. Try to revert form

**Expected behavior**
Form reverted successfully.

**Screenshots**
No screenshots available.

**Additional context**
[Savegames.zip](https://github.com/Keizaal/Keizaal/files/8599694/Savegames.zip)

**Comment by TateTaylorUSA** [comment]
Try removing [Better Telekinesis](https://www.nexusmods.com/skyrimspecialedition/mods/42906) from Keizaal.

Additionally, I don't see you on Discord. Are you in my server?

**Comment by Arioh002** [comment]
Arioh002#2638 - added myself to your server, please check again.
Also there is no "Better telekinesis" as far as I can see - please check attached active mods list from MO.
[Active mods.txt](https://github.com/Keizaal/Keizaal/files/8605185/Active.mods.txt)

**Comment by Arioh002** [comment]
![image](https://user-images.githubusercontent.com/2345961/166301193-575b7868-9fc2-4498-a5ab-f83608eef157.png)

**Comment by TateTaylorUSA** [comment]
Cannot replicate.
I will reopen this if you continue to experience the issue on 6.4.2.
