### ISSUE TITLE
A Night to Remember CTD on fast travel.

### ISSUE THREAD

**Issue by SajochiSama** [Keizaal/Keizaal#233]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder. If possible, please also attach a copy of your most recent save before the issue occurred.**

**Discord Username**
Sajochi#2482

**Keizaal version**
6.4.2

**Describe the bug**
When forced to fast travel after Sam's drinking game, there is a consistent CTD. Using regular fast travel does not appear to cause the issue.
**To reproduce**
Find Sam Guevenne in the inn at Rorikstead and play the drinking game. When sent to the Temple of Dibella, area attempts to load and then CTD. Most recent save and crash log is attached.
**Expected behavior**
A night to remember should begin.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
[crash-2022-05-28-16-34-13.log](https://github.com/Keizaal/Keizaal/files/8791588/crash-2022-05-28-16-34-13.log)
[saves.zip](https://github.com/Keizaal/Keizaal/files/8791593/saves.zip)

**Comment by TateTaylorUSA** [comment]
Unable to replicate this bug.
